
stages:
  - build
  - test

build:
  image: openjdk:11
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - /build/libs/*.jar
    expire_in: 3 days

test:
  image: openjdk:11
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - /build/test-results/test/*.xml
    expire_in: 3 days